---
- function:
    name: splineStart()
    description: 样条运动开始
    arguments:
      - name: n/a
        type: n/a
        description: n/a
    return: 成功：[0],失败：[errcode]
  
- function:
    name: SplinePTP(joint_pos,desc_pos,tool,user,vel,acc,ovl)
    description: 样条运动PTP
    arguments:
      - name: joint_pos
        type: float
        description: 目标关节位置，单位[°]
      - name: desc_pos
        type: float
        description: 目标笛卡尔位姿，单位[mm][°]
      - name: tool
        type: int
        description: 工具号，[0~14]
      - name: user
        type: int
        description: 工件号，[0~14]
      - name: vel
        type: float
        description: 速度，范围[0~100]，暂不开放，默认为0
      - name: acc
        type: float
        description: 加速度，范围[0~100]，暂不开放，默认为0
      - name: ovl
        type: float
        description: 速度缩放因子，[0~100]
    return: 成功：[0],失败：[errcode]

- function:
    name: SplineEnd()
    description: 样条运动结束
    arguments:
      - name: n/a
        type: n/a
        description: n/a
    return: 成功：[0],失败：[errcode]