---
- function:
    name: MoveL(joint_pos,desc_pos,tool,user,vel,acc,ovl,exaxis_pos,blendR,search,offset_flag,offset_pos)
    description: 笛卡尔空间直线运动
    arguments:
      - name: joint_pos
        type: float
        description: 目标关节位置，单位[°]
      - name: desc_pos
        type: float
        description: 目标笛卡尔位姿，单位[mm][°]
      - name: tool
        type: int
        description: 工具号，[0~14]
      - name: user
        type: int
        description: 工件号，[0~14]
      - name: vel
        type: float
        description: 速度百分比，[0~100]
      - name: acc
        type: float
        description: 加速度百分比，[0~100]，暂不开放
      - name: ovl
        type: float
        description: 速度缩放因子，[0~100]
      - name: exaxis_pos
        type: float
        description: 外部轴1位置~外部轴4位置,单位mm
      - name: blendR
        type: int
        description: [-1.0]-运动到位(阻塞)，[0~500]-平滑时间(非阻塞)，单位[ms]
      - name: search
        type: int
        description: [0]-不焊丝寻位，[1]-焊丝寻位
      - name: offset_flag
        type: int
        description: [0]-不偏移，[1]-工件/基坐标系下偏移，[2]-工具坐标系下偏移
      - name: offset_pos
        type: float
        description: 位姿偏移量，单位[mm][°]
    return: 成功：[0],失败：[errcode]