---
- function:
    name: NewSpiral(joint_pos,desc_pos,tool,user,vel,acc,exaxis_pos,ovl,offset_flag,offset_pos,param)
    description: 笛卡尔空间螺旋线运动
    arguments:
      - name: joint_pos
        type: float
        description: 目标关节位置，单位[°]
      - name: desc_pos
        type: float
        description: 目标笛卡尔位姿，单位[mm][°]
      - name: tool
        type: int
        description: 工具号，[0~14]
      - name: user
        type: int
        description: 工件号，[0~14]
      - name: vel
        type: int
        description: 速度百分比，[0~100]
      - name: acc
        type: int
        description: 加速度百分比，[0~100]，暂不开放
      - name: exaxis_pos
        type: float
        description: 外部轴1位置~外部轴4位置,单位mm
      - name: ovl
        type: int
        description: 速度缩放因子，[0~100]
      - name: offset_flag
        type: int
        description: [0]-不偏移，[1]-工件/基坐标系下偏移，[2]-工具坐标系下偏移
      - name: offset_pos
        type: float
        description: 位姿偏移量，单位[mm][°]
      - name: param
        type: list[int]
        description: [circle_num,circle_angle,rad_init,rad_add,rotaxis_add,rot_direction]，circle_num:螺旋圈数，circle_angle:螺旋倾角，rad_init:螺旋初始半径，rad_add:半径增量，rotaxis_add:转轴方向增量，rot_direction:旋转方向，0-顺时针，1-逆时针
    return: 成功：[0],失败：[errcode]